### ISSUE TITLE
Status Code 403 and status message - Forbidden

### ISSUE THREAD

**Issue by MukFlex** [martindale/soundtrack.io-android#5]
I am unable to connect to url, after debugging I get status code 403 with error message Forbidden in parseHTTPStatus method WebSocketReade class.

But when I try to connect with same url in other project then it work. It also work in IOS.
https://github.com/njovy/AppRTCDemo ( Please check in libs).

Please suggest what going wrong.

**Comment by martindale** [comment]
Try changing URL to a specific room; i.e., `wss://soundtrack.io/stream/websocket` becomes `wss://coding.soundtrack.io/stream/websocket`

Rooms list: https://soundtrack.io

**Comment by martindale** [comment]
Did this resolve the issue?

**Comment by MukFlex** [comment]
Yes, In AppRTC  video call  turn server is different . Change  origin in WebSocketWriter.java
  write("Origin: " +"https://www.google.com");
